CREATE DATABASE IF NOT EXISTS EJERCICIO1;
USE EJERCICIO1;
CREATE TABLE IF NOT EXISTS TRIANGULO(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LADO1 INT NOT NULL,
    LADO2 INT NOT NULL,
    LADO3 INT NOT NULL,
    TIPOTRIANGULO VARCHAR(30) NOT NULL
    );